In [1]:
# %pip install pandas

In [2]:
import numpy as np
import pandas as pd 
import random

In [3]:
rewards = np.array([
    [-1, -1, -1, -1,  0,  -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1 , 0 ,-1 , -1],
    [-1,  0,  0 ,-1  ,0 , -1],
    [0, -1, -1 , 0 ,-1 ,100],
    [-1,  0, -1, -1,  0, 100] 
])
pd.DataFrame(rewards)

0  1  2  3  4    5
0 -1 -1 -1 -1  0   -1
1 -1 -1 -1  0 -1  100
2 -1 -1 -1  0 -1   -1
3 -1  0  0 -1  0   -1
4  0 -1 -1  0 -1  100
5 -1  0 -1 -1  0  100

In [4]:
print(rewards[2])
for i in enumerate(rewards[2]):
    print(i)


[-1 -1 -1  0 -1 -1]
(0, -1)
(1, -1)
(2, -1)
(3, 0)
(4, -1)
(5, -1)


In [5]:
def set_initial_state():
    return np.random.randint(0, 6)

In [6]:
set_initial_state()

5

In [7]:
def get_action(current_state, reward_matrix):
    available_action = []
    print("reward_matrix","\n",reward_matrix)    
    for action in enumerate(reward_matrix[current_state]):     
        if action[1]!= -1:            
            available_action.append(action[0]) 
    print("Random choice of action from",available_action,"is", random.choice(available_action))           
    return random.choice(available_action)

In [8]:
q_matrix = np.zeros([6,6])
print(q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
def take_action(current_state, reward_matrix, gamma):
    
    action = get_action(current_state, reward_matrix)
    
    #Current State, Action Reward
    current_sa_reward = reward_matrix[current_state, action]
    
    # New State, Action Reward
    q_sa_value = max(q_matrix[action,])

    # Current Q state
    q_current_state = current_sa_reward + (gamma * q_sa_value)

    # Update Q matrix
    q_matrix[current_state,action] = q_current_state

    new_state = action
    print("q_matrix ","\n",q_matrix)
    print("********************************************************************")
    if new_state == 5:
        print("Reached Goal!")
    else: 
        print(f"Old State:{current_state} New State: {new_state}")
        
    return new_state


In [10]:
def run_episode(initial_state,reward_matrix, gamma): 
    new_state =  take_action(initial_state, reward_matrix, gamma)
    while True:
        if new_state == 5:
            break
        else:
            new_state =  take_action(new_state, reward_matrix, gamma)            
            

In [11]:
def train(episodes, reward_matrix, gamma):
    print("Training...")

    for episode in range(episodes):
        print("Starting Episode")

        # Set initial State
        initial_state = set_initial_state()
        print("Initial State:", initial_state)

        # Initalise Episode(Get Action, Take Action to get new state)
        run_episode(initial_state, reward_matrix, gamma)

        print("Ending Episode")

    print("Training completed!")
    
    return q_matrix


In [12]:
gamma = 0.8

# Get Q table
q_table = train(2, rewards, gamma)

print("Final Q Table: ", q_table)

Training...
Starting Episode
Initial State: 2
reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]
Random choice of action from [3] is 3
q_matrix  
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
********************************************************************
Old State:2 New State: 3
reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [  0  -1  -1   0  -1 100]
 [ -1   0  -1  -1   0 100]]
Random choice of action from [1, 2, 4] is 1
q_matrix  
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
********************************************************************
Old State:3 New State: 4
reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1

In [13]:
def get_max_reward(q_table):
    max_reward = max(q_table[q_table.nonzero()])
    return max_reward

In [14]:
def optimal_path(q_table):
    path=[]
    path_index = q_table.nonzero()
    for i in path_index:
        path.append(i[0])
    return path


In [15]:
Q_optimal_path = optimal_path(q_table)
max_reward = get_max_reward(q_table)
print(Q_optimal_path)
print(max_reward)

[1, 5]
100.0
